### ISSUE TITLE
关于tcpConnction.h中的loop的一点疑问

### ISSUE THREAD

**Issue by xt1234567** [S1mpleBug/muduo_cpp11#1]
EventLoop *loop_; // 这里绝对不是baseLoop 因为TcpConnection都是subLoop里面管理的
 作者您好，您对muduo库的讲解让我受益匪浅，在这里我有一个疑问，这里你说TcpConnection中的loop_绝对不是baseLoop，但muduo它本身是支持单reactor以及多reactor的，如果不设置多reactor，也就是说只有一个reactor，那这个loop不就是baseLoop吗？我可能理解的有问题，所以期待您的解答，感谢！

**Comment by S1mpleBug** [comment]
感谢反馈，这个注释是我在考虑多`Reactor`时写的，确实有问题。当为单`Reactor`的情况时，在`TcpServer.cc`当中创建`TcpConnection`对象时，`ioLoop`指向的是`threadPool_->getNextLoop()`返回的`EventLoop *baseLoop_`，`TcpServer`中`TcpConnection`对象传入的第一个参数`ioLoop`即为指向`baseLoop`的指针，你说的没错。
