### ISSUE TITLE
服务器终止后，客户端才能收到信息

### ISSUE THREAD

**Issue by xyygudu** [S1mpleBug/muduo_cpp11#3]
你好，看了你bilibili上的讲解受益匪浅，但是运行代码遇到了如下问题：
启动testserver后，在浏览器上输入127.0.0.01:8002访问一直无结果返回客户端，只有当终止服务器运行时，浏览器才能收到消息，但是很奇怪，用telnet又能够正常发送和接收，请问是那里出了问题呢，谢谢

**Comment by S1mpleBug** [comment]
这个项目没有实现HTTP模块功能，所以浏览器上无法展示静态文本页面
